

## 1.5 넘파이  

### 배열의 속성들  
| 속성           | 의미               | 예시 값              |  
| ------------ | ---------------- | -------------------- |
| **dtype**    | 원소의 자료형이 무엇인지 알려줌    |   int32, float64, bool                     |  
| **shape**    | 배열의 구조 (행, 열, …)을 알려줌 |   (2, 3) → 2행 3열                          |  
| **ndim**     | 차원 수             | 1차원, 2차원, 3차원 (얼마나 감싸졌는지로 쉽게 확인 가능)       |  
| **size**     | 전체 원소 개수         | 6  (차원 구분 없이 모든 원소 갯수 세기)                   |  
| **itemsize** | 원소 하나의 크기(byte)  | 8  (배열의 각 원소가 메모리에서 차지하는 바이트 크기)        |  


### 1.5.1 넘파이 가져오기  

In [ ]:
# !uv add numpy

In [2]:
import numpy as np

### 1.5.2 넘파이 배열 생성하기  

In [ ]:
x = np.array([1.0, 2.0, 3.0])
# 파이썬 리스트를 인수로 받아 넘파이 라이브러리가 제공하는 특수한 형태의 배열(numpy.ndarray)을 반환
# 1차원 배열(벡터) 생성

print(x)

[1. 2. 3.]


In [ ]:
type(x)

numpy.ndarray

### 1.5.3 넘파이의 산술 연산  

In [ ]:
x = np.array([1.0, 2.0, 3.0])  # x라는 벡터
y = np.array([2.0, 4.0, 6.0])  # y라는 벡터

x + y  # 원소별 덧셈

array([3., 6., 9.])

In [ ]:
x - y  # 원소별 뺄셈

array([-1., -2., -3.])

In [ ]:
x * y  # 원소별 곱셈

array([ 2.,  8., 18.])

In [ ]:
x / y  # 원소별 나눗셈

array([0.5, 0.5, 0.5])

In [ ]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0

array([0.5, 1. , 1.5])

### 1.5.4 넘파이의 N차원 배열  

In [ ]:
A = np.array([[1, 2], [3, 4]])  # 2차원 배열인 행렬을 만듬 (2행 2열)
print(A)

[[1 2]
 [3 4]]


In [ ]:
A.shape  # 해당 배열(행렬)의 행과 열을 수를 tuple 형태로 반환합니다.
# = 2행 2열

(2, 2)

In [ ]:
A.dtype  # 내부 원소들의 자료현이 무엇인지 파악합니다.

dtype('int64')

In [ ]:
B = np.array([[3, 0], [0, 6]])  # B라는 2차원 배열인 행렬을 만듬
A + B  # 기본 사칙 연산 + 더하기

array([[ 4,  2],
       [ 3, 10]])

In [ ]:
A * B  # 기본 사칙 연산 * 곱하기

array([[ 3,  0],
       [ 0, 24]])

In [ ]:
print(A)  # 단순 A라는 배열을 출력합니다.

[[1 2]
 [3 4]]


In [ ]:
# 브로트 캐스트

A * 10  # A라는 행렬 * 값이 하나뿐인 스칼라
# 형상이 다른 행렬끼리 계산이 가능합니다.
# 브로캐스트를 통해 자동으로 numpy가 스칼라의 shape를 [[10,10], [10,10]]으로 만들어서 계산합니다.

array([[10, 20],
       [30, 40]])

### 1.5.5 브로드캐스트  

In [ ]:
A = np.array([[1, 2], [3, 4]])  # 2차원 배열 = 행렬
B = np.array([10, 20])  # 이 벡터의 shape가 브로드캐스트되면 [[10,20], [10,20]]입니다.
A * B  # 행렬 shape가 (2,2) * (2,2) 와 같이 계산이 되어 정상적인 연산 결과를 확인할 수 있습니다.

array([[10, 40],
       [30, 80]])

### 1.5.6 원소 접근  

In [ ]:
X = np.array([[51, 55], [14, 19], [0, 4]])  # 3행 2열
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [ ]:
# 마치 python list에서 인덱스로 각각의 원소에 접근했듯이 인덱스를 통해 행렬에 접근합니다.
X[0]  # 현재 행렬의 0번쨰 값을 확인할 수 있습니다.

array([51, 55])

In [ ]:
X[0][1]  # (0, 1) 위치의 원소
# X라는 행렬의 0번째 원소의 1번째 원소를 의미합니다.

np.int64(55)

In [ ]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [ ]:
# 🆘 flatten
X = X.flatten()  # X를 1차원 배열로 변환(평탄화)

print(X)

# 궁금증 test
XXX = np.array(
    [
        [[51, 55], [14, 19], [0, 4]],
        [[51, 55], [14, 19], [0, 4]],
        [[51, 55], [14, 19], [0, 4]],
    ]
)
XXX = XXX.flatten()
print(XXX)

[51 55 14 19  0  4]
[51 55 14 19  0  4 51 55 14 19  0  4 51 55 14 19  0  4]


In [ ]:
# X는 현재 1차원 배열임
# 🆘 X 배열에서 인덱스 0,2,4에 해당되는 값만 별도 배열로 만듭니다.
X[np.array([0, 2, 4])]  # 인덱스가 0, 2, 4인 원소 얻기
# 원본을 그대로 두고, 새로운 배열을 반환.

# ------------------------------------

XXXXX = X[np.array([0, 2, 4])]  # 원본을 그대로 두고, 새로운 배열을 반환.
print(XXXXX)  # 원본을 그대로 두고, 새로운 배열을 반환.

print(X)  # 원본이 변경되지 않음을 확인.

[51 14  0]
[51 55 14 19  0  4]


In [ ]:
# X는 현재 1차원 배열임
X > 15
# 🆘 X 배열에서 15보다 큰 것은 True, 작으면 False를 반환

array([ True,  True, False,  True, False, False])

In [ ]:
X[X > 15]
# 🆘 X 배열에서 15보다 큰 값의 인덱스를 파악 -> 해당 인덱스의 값만 가지고 새로운 배열을 반환

array([51, 55, 19])