<br><br>

---

## 🟢 3.3 다차원 배열의 계산  

### 🟡 3.3.1 다차원 배열  

In [110]:
import numpy as np

A = np.array([1, 2, 3, 4])  # A라는 넘파이 배열
print(A)

[1 2 3 4]


In [111]:
np.ndim(A)  # A라는 넘파이 배열의 차원이 몇 차원인지 알 수 있음

1

In [112]:
A.shape  # A라는 넘파이 배열의 행렬갯수를 나타냄

(4,)

In [113]:
A.shape[0]  # A라는 넘파이 배열의 행에 대한 갯구를 나타맨

4

In [114]:
B = np.array([[1, 2], [3, 4], [5, 6]])  # B라는 2차원 넘파이 배열을 만듬print(B)

In [115]:
np.ndim(B)  # B라는 넘파이 배열이 몇 차원인지 알려준다.

2

In [116]:
B.shape  # B라는 넘파이 배열의 형태(행렬를 갯수)를 알 수 있다.

(3, 2)

### 🟡 3.3.2 행렬의 곱  

- 기본적으로 2개의 input을 받음. (2개 이상 시 복잡해짐)  
- 양쪽 array의 원소 개수가 불일치한다면, ValueError가 발생한다. 고차원의 dot 연산에서도 곱할 element의 원소 개수가 일치하는지 꼭 체크하기.  

- 1차원 넘파이 배열을 행렬곱 예시  
    - <img src="image_ch03/1차원_배열_행렬곱.png" alt="행렬곱" width="30%">  

- 2차원 넘파이 배열을 행렬곱 예시  
    - <img src="image_ch03/2차원_배열_행렬곱.png" alt="행렬곱" width="30%">  

<br>

#### ⚫ 예제1 - 행렬곱  
- 같은 차원, 같은 형태  

In [117]:
A = np.array([[1, 2], [3, 4]])  # A라는 2차원 넘파이 배열
A.shape  # A라는 넘파이 배열을 형태(행,렬)을 나타냄 = (2, 2)

(2, 2)

In [118]:
B = np.array([[5, 6], [7, 8]])  # B라는 2차원 넘파이 배열
B.shape  # B라는 넘파이 배열을 형태(행,렬)을 나타냄 = (2, 2)

(2, 2)

In [119]:
np.dot(A, B)
# shape가 같은 A라는 2차원 넘파일 배열과 B라는 2차원 넘파이 배열을 곱한다.

array([[19, 22],
       [43, 50]])

#### 🔥 알아두기  
- np.dot(A, B)와 np.dot(B, A) 는 다른 값이 될 수 있다는 점.  
- 행렬의 곱에서는 피연산자의 순서가 다르면 결과도 다름.  


<br>

#### ⚫ 예제2 - 행렬곱  
- 계산이 가능하려면 `앞자리 행렬의 열 갯수`과 `뒷자리 행렬의 행 갯수`가 같아야 한다.  


In [120]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # A라는 (2, 3) 행렬
print(f"차원 : {A.ndim}차원")
print(f"형태 : {A.shape[0]}행, {A.shape[1]}열")

차원 : 2차원
형태 : 2행, 3열


In [121]:
B = np.array([[1, 2], [3, 4], [5, 6]])  # B라는 (3, 2) 행렬
print(f"차원 : {B.ndim}차원")
print(f"형태 : {B.shape[0]}행, {B.shape[1]}열")

차원 : 2차원
형태 : 3행, 2열


In [122]:
# A의 열이 3이고, B의 행이 3이기 때문에 행렬 곱하기 계산이 가능하다.
np.dot(A, B)  # A 행렬과 B 행렬 곱하기

array([[22, 28],
       [49, 64]])

In [123]:
# 만약에 C라는 행렬이 있다고 가정해보자!
C = np.array([[1, 2], [3, 4]])  # C라는 (2,2) 행렬
C.shape

(2, 2)

In [124]:
A.shape  # A 행렬과 계산이 가능할까???

(2, 3)

In [125]:
# 다음 코드는 아래 주석을 풀어 실행하면 ValueError를 일으킵니다.
# np.dot(A, C)  # A행렬 (2,3)과 C행렬 (2,2)를 계산할 수 없습니다. 에러가 납니다.
# 결과: ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) ! = 2 (dim 0)

# 계산을 하지 못하는 이유는 ⤵️

- A행렬 (2,3)과 C행렬 (2,2)를 계산할 수 없는 이유는???  
    - 🔥 다차원 배열을 곱하려면 두 (행, 렬)의 대응하는 차원의 원소 수를 일치시켜야 합니다.  
        - <img src="image_ch03/차원_원소_수_일치1.png" alt="행렬곱" width="30%">  
        - <img src="image_ch03/차원_원소_수_일치2.png" alt="행렬곱" width="50%">  

<br>

#### ⚫ 예제3 - 행렬곱  


In [126]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])  # A라는 (3,2) 행렬
A.shape

(3, 2)

In [127]:
B = np.array([7, 8])  # B라는 1차원 넘파이 행렬 (Transposit 한다.)
B.shape  # Transposit으로 2행이라고 생각한다.

(2,)

In [128]:
np.dot(A, B)  # 계산 가능
# 1 * 7 + 2 * 8 = 23
# 3 * 7 + 4 * 8 = 53
# 5 * 7 + 6 * 8 = 83
# [[23], [53], [83]] => Transposit => [23, 53, 83]

array([23, 53, 83])

<br>

### 🟡 3.3.3 신경망에서의 행렬 곱  

In [129]:
X = np.array([1, 2])  # X라는 1차원 넘파이 배열
X.shape  # X라는 1차원 넘파이 배열은 (2,)이다.

(2,)

In [130]:
W = np.array([[1, 3, 5], [2, 4, 6]])  # W라는 2차원 넘파이 배열
print(W)  # W라는 2차원 넘파이 배열 출력 확인

[[1 3 5]
 [2 4 6]]


In [131]:
W.shape  # W라는 2차원 넘파이 배열은 (2, 3)이다.

(2, 3)

In [132]:
Y = np.dot(X, W)  # X(입력값)와 W(가중치) 곱하기
print(Y)  # 결과값 출력

[ 5 11 17]


<br><br>

## 🟢 3.4. 3층 신경망 구현하기  

### 🟡 3.4.2. 각 층의 신호 전달 구현하기 (page 82~88)  

- 입력값 >>> 가중치 >>> 편향  
    - 기존 `x * w` 를 `행렬곱`으로 생각하면 이렇게 된다.  
    - <img src="image_ch03/69_1층.png" alt="신경망과정" width="40%">  
- 선형대수 식으로 나타내고, Transposit 하기  
    - <img src="image_ch03/70_행렬식으로바꾸기.png" alt="신경망과정" width="40%">  
    - <img src="image_ch03/71_입력층,가중치,편향.png" alt="신경망과정" width="40%">  

- `입력층`에서 `1층`으로 신호 전달  
    - **sigmoid(입력값(x) * 가중치(w) + 편향(b))**  
    - <img src="image_ch03/72_입력층-1층.png" alt="신경망과정" width="40%">  

In [133]:
X = np.array([1.0, 0.5])  # 입력값 (1차원 넘파이 배열)
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])  # 가중치 (2차원 넘파이 배열)
B1 = np.array([0.1, 0.2, 0.3])  # 편향 (1차원 넘파이 배열)

print(W1.shape)  # (2, 3)

(2, 3)


In [134]:
print(X.shape)  # (2,)

(2,)


In [135]:
print(B1.shape)  # (3,)

(3,)



In [136]:
A1 = np.dot(X, W1) + B1
# 입력값 X(2,)와 가중치 W1(2,3)를 곱하는 것이 가능하기 때문에 곱해주면결 과를 1차원 넘파이 배열 (3,)이 나옴.
# 여기에 자리수가 맞는 B1(편향)(3,)을 더해줌.

In [137]:
Z1 = sigmoid(A1)  # 입력값, 가중치, 편향이 계산된 결과값(3,)을 sigmoid 함수에 넣음.

print(A1)  # [0.3, 0.7, 1.1]

[0.3 0.7 1.1]


In [138]:
print(Z1)  # 시그모이드 함수 결과값 = [0.57444252, 0.66818777, 0.75026011]

[0.57444252 0.66818777 0.75026011]


Z1이라는 특정 노드는 다음 층으로 넘어가서 가중치와 편향으로 또 계산됨.  





In [ ]:
# Z1 shape (3,)

W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
# 가중치 ((3,3)이기 때문에 Z1과 곱하기 가능)

B2 = np.array([0.1, 0.2])  # B2(편향) 이라는 넘파이 배열

print(Z1.shape)  # (3,)

(3,)


In [140]:
print(W2.shape)  # (3, 2)

(3, 2)



In [141]:
print(B2.shape)  # (2,)

(2,)


In [ ]:
A2 = (
    np.dot(Z1, W2) + B2
)  # 입력층에서 계산된 Z1(3,)  *  다음층으로 가는 가중치 W2(3, 2) + B2(편향)
print(f"A2: {A2}")

A2: [0.51615984 1.21402696]


In [143]:
Z2 = sigmoid(A2)
print(f"Z2: {Z2}")

Z2: [0.62624937 0.7710107 ]


In [ ]:
def identity_function(x):  # 항등함수를 만듬
    return x


W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)  # 혹은 Y = A3

<br>

### 🟡 3.4.3 구현 정리  (page 89)  
- 위에서 했던 구현을 다시 코드로 정리해봅시다.  

<img src="image_ch03/80_1층.png" alt="신경망과정" width="30%">  
<img src="image_ch03/81_2층.png" alt="신경망과정" width="30%">  
<img src="image_ch03/82_3층.png" alt="신경망과정" width="30%">  


In [ ]:
def init_network():  # 함수 만들기 (내가 원하는 가중치와 편향을 정해줌)
    network = {}  # network라는 dictionary
    network["W1"] = np.array(
        [[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]
    )  # w1(가중치) 키를 가진 : (2,3) 2차원 넘파이 배열
    network["b1"] = np.array(
        [0.1, 0.2, 0.3]
    )  # b1(편향) 키를 가진 : (3,) 1차원 넘파이 배열
    network["W2"] = np.array(
        [[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]]
    )  # w2(가중치) 키를 가진 : (3,2) 2차원 넘파이 배열
    network["b2"] = np.array([0.1, 0.2])  # b2(편향) 키를 가진 : (2,) 1차원 넘파이 배열
    network["W3"] = np.array(
        [[0.1, 0.3], [0.2, 0.4]]
    )  # w3(가중치) 키를 가진 : (2,2) 2차원 넘파이 배열
    network["b3"] = np.array([0.1, 0.2])  # b3(편향) 키를 가진 : (2,) 1차원 넘파이 배열

    return network


def forward(network, x):  # forward 함수 만들기 (매개변수로 netword와 x(입력값)를 가짐)
    W1, W2, W3 = (
        network["W1"],
        network["W2"],
        network["W3"],
    )  # network 인수는 dictionary이다. 필요한 값을 가져와서 unpacking
    b1, b2, b3 = (
        network["b1"],
        network["b2"],
        network["b3"],
    )  # network 인수는 dictionary이다. 필요한 값을 가져와서 unpacking

    a1 = np.dot(x, W1) + b1  # 넘파이 행렬곱(입력값 * 가중치1) + 편향1
    z1 = sigmoid(a1)  # 시그모이드 함수로 계산 후 현재층 계산 끝
    # 다음 층으로 넘어가서
    a2 = np.dot(z1, W2) + b2  # 넘파이 행렬곱(이전 층 결과값 * 가중치2) + 편향2
    z2 = sigmoid(a2)  # 시그모이드 함수로 계산 후 현재층 계산 끝
    # 다음 층으로 넘어가서
    a3 = np.dot(z2, W3) + b3  # 넘파이 행렬곱(이전 층 결과값 * 가중치3) + 편향3

    y = identity_function(a3)  # 항등함수에 a3값을 넣어 결과를 반환
    # 출력층의 활성화함수는 시그마로 표시!

    return y  # 최종 y 반환

In [ ]:
# 위 정의한 함수를 실제 사용하기

network = (
    init_network()
)  # 먼저 정해놓은 가중치와 편향을 dictionary에 넣어 반환하는 함수를 실행하여 network 변수에 넣습니다.
x = np.array([1.0, 0.5])  # x라는 입력갑.. 즉 (2,) 1차원 넘파이 배열
y = forward(
    network, x
)  # forward 함수에 x 인수와 network 인수를 넣어 '입력층', '1층', '2층' (총 3층)까지 계산 될 수 있도록 합니다.

# 🔥 forward 함수의 상세 계산 과정은 시간상 생략.. 다음에 복습할 때 직접 주석으로 적어보기

print(y)  # [ 0.31682708 0.69627909]    # 결과값 출력

[0.31682708 0.69627909]


<br><br>

---

## 🟢 3.5 출력층 설계하기  

### 🟡 3.5.1. `항등 함수`와 `소프트맥스 함수` 구현하기  (page 91)  
- 항등함수는 항상 같은 값이 그대로 나오는 것  

- 소프트맥스 함수식  

<img src="image_ch03/84_소프트맥스함수식.png" alt="Softmax_변환" width="60%">  
<img src="image_ch03/86_소프트맥스_함수_그림.png" alt="Softmax_변환" width="20%"> 
    
- 소프트맥스 과정  
    - <img src="image_ch03/85_Softmax_변환.png" alt="Softmax_변환" width="50%">  



- 지수함수  

In [ ]:
a = np.array([0.3, 2.9, 4.0])  # a 라는 (3,) 1차원 넘파이 배열

exp_a = np.exp(a)  # a라는 1차원 넘파이 배열을 지수함수에 넣어 반환하고 exp_a에 넣음.
# 🔥 지수 함수 (exponential function) (넘파이 내장함수)
# 지수함수란,
# 거듭제곱의 지수를 변수로 하고, 정의역을 실수 전체로 정의하는 초월함수이다. 로그 함수의 역함수이다.


print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [ ]:
sum_exp_a = np.sum(exp_a)
# 지수 함수의 합 (exp_a(지수함수에서 반환된 결과)를 모두 더함)

print(sum_exp_a)  # 더해진 값 출력 확인

74.1221542101633


In [ ]:
y = exp_a / sum_exp_a  # normalize(정규화)를 통해서 0~1사이의 값으로 바꿈
print(y)  # 정규화된 값 출력 확인

[0.01821127 0.24519181 0.73659691]


- `소프트맥스 함수`로 만들기  

In [ ]:
def softmax(a):
    exp_a = np.exp(a)
    #

    sum_exp_a = np.sum(exp_a)
    # 지수 함수의 합 (exp_a(지수함수에서 반환된 결과)를 모두 더함)

    y = exp_a / sum_exp_a
    # normalize(정규화)를 통해서 0~1사이의 값으로 바꿈

    return y

#### ❓ normalize(정규화) 설명  
- 목적: 데이터의 크기를 0~1 사이로 맞추는 것  
- 방법: 각 값 ÷ 전체 합 or (값 - 최소값) ÷ (최대값 - 최소값)  
- 결과: 모든 값이 0과 1 사이  

<br>

### 🟡 3.5.2. 소프트맥스 함수 구현 시 주의점  

- Softmax Overflow 예시  

In [ ]:
# Softmax Overflow 예시
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))  # 소프트맥스 함수의 계산
# 결과는 제대로 계산되지 않는다. => Overflow 발생

/tmp/ipykernel_12231/3427171853.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))  # 소프트맥스 함수의 계산 (제대로 계산되지 않는다)
/tmp/ipykernel_12231/3427171853.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))  # 소프트맥스 함수의 계산 (제대로 계산되지 않는다)


array([nan, nan, nan])

In [ ]:
# 배열의 값중에 가장 큰 값을 뺴주는 노멀라이즈를 해주는 작업.
c = np.max(a)  
a - c

array([  0, -10, -20])

In [ ]:
# 오버플로우 방지를 위해 노멀라이즈가 추가된 소프트맥스 계산.
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [ ]:
def softmax(a):
    c = np.max(a)           # 먼저 a인수(넘파이 배열)에서 노멀라이즈를 해주기 위해서 배열 중 최댓값을 찾아서 C에 넣음.
    exp_a = np.exp(a - c)   # 오버플로 대책 - 전체 a배열에서 각각 최댓값을 빼주고, 지수함수 적용.
    sum_exp_a = np.sum(exp_a)   # 그리고 모든 값을 더해준다.
    y = exp_a / sum_exp_a       # 마지막으로 exp_a / sum_exp_a 나누기 계산을 한다.

    return y    # 최종 y값 반환

<br>

### 🟡 3.5.3. 소프트맥스 함수의 특징  

In [ ]:
a = np.array([0.3, 2.9, 4.0])       # 넘파이 배열
y = softmax(a)                      # a 배열을 소프트맥스 함수 적용

print(y)                            # 소프트맥스 함수를 적용한 a 배열 출력 및 확인
np.sum(y)                           # 특징 - 모두 더한 결과값의 합은 1이 된다.

[0.01821127 0.24519181 0.73659691]


np.float64(1.0)